const List = [
  {
    key: "001",
    productName: "میلگرد",
    manufactureName: "فولاد امین",
    manufactureIcon :"ahan-folod-amin.png",
    productDetails: "آجدار",
    productPrice : "4,700",
    productAvailable: "موجود",
    productFlag: "true",
    productChartLink: "",
    storeLocation: "تهران",
    fakeCount:"1000",
    chartData :[55, 1, 15, 120],
  },
  {
    key: "002",
    productName: "میلگرد",
    manufactureName: "فولاد میانه",
    manufactureIcon : "folad-mianeh.png",
    productDetails: "آجدار",
    productPrice : "5,800",
    productAvailable: "موجود",
    productFlag: "true",
    productChartLink: "",
    storeLocation: "تهران",
    fakeCount:"500",
    chartData :[5, 10, 5, 20],
  },
  {
    key: "003",
    productName: "میلگرد",
    manufactureName: "فولاد خراسان",
    manufactureIcon : "milgerd-khorasan.png",
    productDetails: "آجدار",
    productPrice : "6,700",
    productAvailable: "ناموجود",
    productFlag: "false",
    productChartLink: "",
    storeLocation: "اصفهان",
    fakeCount:"300",
    chartData :[40, 100, 120, 12],
  },
];

export default List;
